# config.yaml
-
  brightness: 58
  contrast: 50
  line_threshold: 200
  black_stone_threshold: 128

# 清晰印刷，棋盘背景灰色
-
  brightness: 75
  contrast: 72
  line_threshold: 155
  black_stone_threshold: 130

# 清晰印刷，棋盘背景灰色, 黑色较浅
-
  brightness: 66
  contrast: 72
  line_threshold: 155
  black_stone_threshold: 130

# 清晰印刷，棋盘背景灰色，黑色棋子偏重
-
  brightness: 67
  contrast: 51
  line_threshold: 132
  black_stone_threshold: 128

# 护眼纸印刷，棋盘背景浅黄色
-
  brightness: 63
  contrast: 58
  line_threshold: 125
  black_stone_threshold: 135
-
  brightness: 80
  contrast: 50
  line_threshold: 180
  black_stone_threshold: 120
